// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/auth.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupVKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=Login,proto3,oneof" json:"Login,omitempty"`
	VkID          string                 `protobuf:"bytes,2,opt,name=VkID,proto3" json:"VkID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupVKRequest) Reset() {
	*x = SignupVKRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupVKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupVKRequest) ProtoMessage() {}

func (x *SignupVKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupVKRequest.ProtoReflect.Descriptor instead.
func (*SignupVKRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SignupVKRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *SignupVKRequest) GetVkID() string {
	if x != nil {
		return x.VkID
	}
	return ""
}

type Enable2FaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Has2Fa        bool                   `protobuf:"varint,2,opt,name=Has2fa,proto3" json:"Has2fa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FaRequest) Reset() {
	*x = Enable2FaRequest{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FaRequest) ProtoMessage() {}

func (x *Enable2FaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FaRequest.ProtoReflect.Descriptor instead.
func (*Enable2FaRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Enable2FaRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Enable2FaRequest) GetHas2Fa() bool {
	if x != nil {
		return x.Has2Fa
	}
	return false
}

type Enable2FaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has2Fa        bool                   `protobuf:"varint,1,opt,name=Has2fa,proto3" json:"Has2fa,omitempty"`
	QrCode        []byte                 `protobuf:"bytes,2,opt,name=QrCode,proto3" json:"QrCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FaResponse) Reset() {
	*x = Enable2FaResponse{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FaResponse) ProtoMessage() {}

func (x *Enable2FaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FaResponse.ProtoReflect.Descriptor instead.
func (*Enable2FaResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Enable2FaResponse) GetHas2Fa() bool {
	if x != nil {
		return x.Has2Fa
	}
	return false
}

func (x *Enable2FaResponse) GetQrCode() []byte {
	if x != nil {
		return x.QrCode
	}
	return nil
}

type Disable2FaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Has2Fa        bool                   `protobuf:"varint,2,opt,name=Has2fa,proto3" json:"Has2fa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FaRequest) Reset() {
	*x = Disable2FaRequest{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FaRequest) ProtoMessage() {}

func (x *Disable2FaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FaRequest.ProtoReflect.Descriptor instead.
func (*Disable2FaRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Disable2FaRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Disable2FaRequest) GetHas2Fa() bool {
	if x != nil {
		return x.Has2Fa
	}
	return false
}

type Disable2FaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has2Fa        bool                   `protobuf:"varint,1,opt,name=Has2fa,proto3" json:"Has2fa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FaResponse) Reset() {
	*x = Disable2FaResponse{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FaResponse) ProtoMessage() {}

func (x *Disable2FaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FaResponse.ProtoReflect.Descriptor instead.
func (*Disable2FaResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Disable2FaResponse) GetHas2Fa() bool {
	if x != nil {
		return x.Has2Fa
	}
	return false
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=Login,proto3" json:"Login,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Has2Fa        bool                   `protobuf:"varint,5,opt,name=Has2fa,proto3" json:"Has2fa,omitempty"`
	IsForeign     bool                   `protobuf:"varint,6,opt,name=IsForeign,proto3" json:"IsForeign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserResponse) GetHas2Fa() bool {
	if x != nil {
		return x.Has2Fa
	}
	return false
}

func (x *UserResponse) GetIsForeign() bool {
	if x != nil {
		return x.IsForeign
	}
	return false
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SignupRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	TwoFactorCode *string                `protobuf:"bytes,3,opt,name=TwoFactorCode,proto3,oneof" json:"TwoFactorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SignInRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignInRequest) GetTwoFactorCode() string {
	if x != nil && x.TwoFactorCode != nil {
		return *x.TwoFactorCode
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserResponse          `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	JWTToken      string                 `protobuf:"bytes,2,opt,name=JWTToken,proto3" json:"JWTToken,omitempty"`
	CSRFToken     string                 `protobuf:"bytes,3,opt,name=CSRFToken,proto3" json:"CSRFToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetJWTToken() string {
	if x != nil {
		return x.JWTToken
	}
	return ""
}

func (x *AuthResponse) GetCSRFToken() string {
	if x != nil {
		return x.CSRFToken
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type LoadDanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dance         []byte                 `protobuf:"bytes,1,opt,name=Dance,proto3" json:"Dance,omitempty"`
	FileFormat    string                 `protobuf:"bytes,2,opt,name=FileFormat,proto3" json:"FileFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDanceRequest) Reset() {
	*x = LoadDanceRequest{}
	mi := &file_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDanceRequest) ProtoMessage() {}

func (x *LoadDanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDanceRequest.ProtoReflect.Descriptor instead.
func (*LoadDanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *LoadDanceRequest) GetDance() []byte {
	if x != nil {
		return x.Dance
	}
	return nil
}

func (x *LoadDanceRequest) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

type LoadDanceByURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	DanceId       string                 `protobuf:"bytes,2,opt,name=DanceId,proto3" json:"DanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDanceByURLRequest) Reset() {
	*x = LoadDanceByURLRequest{}
	mi := &file_proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDanceByURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDanceByURLRequest) ProtoMessage() {}

func (x *LoadDanceByURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDanceByURLRequest.ProtoReflect.Descriptor instead.
func (*LoadDanceByURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LoadDanceByURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LoadDanceByURLRequest) GetDanceId() string {
	if x != nil {
		return x.DanceId
	}
	return ""
}

type LoadDanceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DanceID             string                 `protobuf:"bytes,1,opt,name=DanceID,proto3" json:"DanceID,omitempty"`
	SegmentsKey         string                 `protobuf:"bytes,2,opt,name=SegmentsKey,proto3" json:"SegmentsKey,omitempty"`
	FullGlbKey          string                 `protobuf:"bytes,3,opt,name=FullGlbKey,proto3" json:"FullGlbKey,omitempty"`
	GlbKeys             []string               `protobuf:"bytes,4,rep,name=GlbKeys,proto3" json:"GlbKeys,omitempty"`
	NumFrames           int32                  `protobuf:"varint,5,opt,name=NumFrames,proto3" json:"NumFrames,omitempty"`
	NumSegments         int32                  `protobuf:"varint,6,opt,name=NumSegments,proto3" json:"NumSegments,omitempty"`
	NumSegmentsRendered int32                  `protobuf:"varint,7,opt,name=NumSegmentsRendered,proto3" json:"NumSegmentsRendered,omitempty"`
	DurationSec         float64                `protobuf:"fixed64,8,opt,name=DurationSec,proto3" json:"DurationSec,omitempty"`
	VideoPath           string                 `protobuf:"bytes,9,opt,name=VideoPath,proto3" json:"VideoPath,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadDanceResponse) Reset() {
	*x = LoadDanceResponse{}
	mi := &file_proto_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDanceResponse) ProtoMessage() {}

func (x *LoadDanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDanceResponse.ProtoReflect.Descriptor instead.
func (*LoadDanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{14}
}

func (x *LoadDanceResponse) GetDanceID() string {
	if x != nil {
		return x.DanceID
	}
	return ""
}

func (x *LoadDanceResponse) GetSegmentsKey() string {
	if x != nil {
		return x.SegmentsKey
	}
	return ""
}

func (x *LoadDanceResponse) GetFullGlbKey() string {
	if x != nil {
		return x.FullGlbKey
	}
	return ""
}

func (x *LoadDanceResponse) GetGlbKeys() []string {
	if x != nil {
		return x.GlbKeys
	}
	return nil
}

func (x *LoadDanceResponse) GetNumFrames() int32 {
	if x != nil {
		return x.NumFrames
	}
	return 0
}

func (x *LoadDanceResponse) GetNumSegments() int32 {
	if x != nil {
		return x.NumSegments
	}
	return 0
}

func (x *LoadDanceResponse) GetNumSegmentsRendered() int32 {
	if x != nil {
		return x.NumSegmentsRendered
	}
	return 0
}

func (x *LoadDanceResponse) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *LoadDanceResponse) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

type LogOutUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=Login,proto3" json:"Login,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutUserRequest) Reset() {
	*x = LogOutUserRequest{}
	mi := &file_proto_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutUserRequest) ProtoMessage() {}

func (x *LogOutUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutUserRequest.ProtoReflect.Descriptor instead.
func (*LogOutUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{15}
}

func (x *LogOutUserRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LogOutUserRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LogOutUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LogOutUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LogOutUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutUserResponse) Reset() {
	*x = LogOutUserResponse{}
	mi := &file_proto_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutUserResponse) ProtoMessage() {}

func (x *LogOutUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutUserResponse.ProtoReflect.Descriptor instead.
func (*LogOutUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{16}
}

type ValidateAndGetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndGetUserRequest) Reset() {
	*x = ValidateAndGetUserRequest{}
	mi := &file_proto_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndGetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndGetUserRequest) ProtoMessage() {}

func (x *ValidateAndGetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndGetUserRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndGetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateAndGetUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetDanceByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DanceId       string                 `protobuf:"bytes,1,opt,name=DanceId,proto3" json:"DanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDanceByIDRequest) Reset() {
	*x = GetDanceByIDRequest{}
	mi := &file_proto_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDanceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDanceByIDRequest) ProtoMessage() {}

func (x *GetDanceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDanceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDanceByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{18}
}

func (x *GetDanceByIDRequest) GetDanceId() string {
	if x != nil {
		return x.DanceId
	}
	return ""
}

type GetMainPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMainPageRequest) Reset() {
	*x = GetMainPageRequest{}
	mi := &file_proto_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMainPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMainPageRequest) ProtoMessage() {}

func (x *GetMainPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMainPageRequest.ProtoReflect.Descriptor instead.
func (*GetMainPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{19}
}

type VideoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoItem) Reset() {
	*x = VideoItem{}
	mi := &file_proto_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoItem) ProtoMessage() {}

func (x *VideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoItem.ProtoReflect.Descriptor instead.
func (*VideoItem) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{20}
}

func (x *VideoItem) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *VideoItem) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type GetMainPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Videos        []*VideoItem           `protobuf:"bytes,2,rep,name=Videos,proto3" json:"Videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMainPageResponse) Reset() {
	*x = GetMainPageResponse{}
	mi := &file_proto_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMainPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMainPageResponse) ProtoMessage() {}

func (x *GetMainPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMainPageResponse.ProtoReflect.Descriptor instead.
func (*GetMainPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetMainPageResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetMainPageResponse) GetVideos() []*VideoItem {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\"J\n" +
	"\x0fSignupVKRequest\x12\x19\n" +
	"\x05Login\x18\x01 \x01(\tH\x00R\x05Login\x88\x01\x01\x12\x12\n" +
	"\x04VkID\x18\x02 \x01(\tR\x04VkIDB\b\n" +
	"\x06_Login\":\n" +
	"\x10Enable2faRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Has2fa\x18\x02 \x01(\bR\x06Has2fa\"C\n" +
	"\x11Enable2faResponse\x12\x16\n" +
	"\x06Has2fa\x18\x01 \x01(\bR\x06Has2fa\x12\x16\n" +
	"\x06QrCode\x18\x02 \x01(\fR\x06QrCode\";\n" +
	"\x11Disable2faRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06Has2fa\x18\x02 \x01(\bR\x06Has2fa\",\n" +
	"\x12Disable2faResponse\x12\x16\n" +
	"\x06Has2fa\x18\x01 \x01(\bR\x06Has2fa\"\x0f\n" +
	"\rEmptyResponse\"\x9c\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x05R\aVersion\x12\x14\n" +
	"\x05Login\x18\x03 \x01(\tR\x05Login\x12\x16\n" +
	"\x06Avatar\x18\x04 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Has2fa\x18\x05 \x01(\bR\x06Has2fa\x12\x1c\n" +
	"\tIsForeign\x18\x06 \x01(\bR\tIsForeign\"A\n" +
	"\rSignupRequest\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"~\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05Login\x18\x01 \x01(\tR\x05Login\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12)\n" +
	"\rTwoFactorCode\x18\x03 \x01(\tH\x00R\rTwoFactorCode\x88\x01\x01B\x10\n" +
	"\x0e_TwoFactorCode\"p\n" +
	"\fAuthResponse\x12&\n" +
	"\x04User\x18\x01 \x01(\v2\x12.auth.UserResponseR\x04User\x12\x1a\n" +
	"\bJWTToken\x18\x02 \x01(\tR\bJWTToken\x12\x1c\n" +
	"\tCSRFToken\x18\x03 \x01(\tR\tCSRFToken\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"s\n" +
	"\x15ChangePasswordRequest\x12 \n" +
	"\vOldPassword\x18\x01 \x01(\tR\vOldPassword\x12 \n" +
	"\vNewPassword\x18\x02 \x01(\tR\vNewPassword\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\tR\x06UserID\"H\n" +
	"\x10LoadDanceRequest\x12\x14\n" +
	"\x05Dance\x18\x01 \x01(\fR\x05Dance\x12\x1e\n" +
	"\n" +
	"FileFormat\x18\x02 \x01(\tR\n" +
	"FileFormat\"C\n" +
	"\x15LoadDanceByURLRequest\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\x12\x18\n" +
	"\aDanceId\x18\x02 \x01(\tR\aDanceId\"\xbb\x02\n" +
	"\x11LoadDanceResponse\x12\x18\n" +
	"\aDanceID\x18\x01 \x01(\tR\aDanceID\x12 \n" +
	"\vSegmentsKey\x18\x02 \x01(\tR\vSegmentsKey\x12\x1e\n" +
	"\n" +
	"FullGlbKey\x18\x03 \x01(\tR\n" +
	"FullGlbKey\x12\x18\n" +
	"\aGlbKeys\x18\x04 \x03(\tR\aGlbKeys\x12\x1c\n" +
	"\tNumFrames\x18\x05 \x01(\x05R\tNumFrames\x12 \n" +
	"\vNumSegments\x18\x06 \x01(\x05R\vNumSegments\x120\n" +
	"\x13NumSegmentsRendered\x18\a \x01(\x05R\x13NumSegmentsRendered\x12 \n" +
	"\vDurationSec\x18\b \x01(\x01R\vDurationSec\x12\x1c\n" +
	"\tVideoPath\x18\t \x01(\tR\tVideoPath\"k\n" +
	"\x11LogOutUserRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x05R\aVersion\x12\x14\n" +
	"\x05Login\x18\x03 \x01(\tR\x05Login\x12\x16\n" +
	"\x06Avatar\x18\x04 \x01(\tR\x06Avatar\"\x14\n" +
	"\x12LogOutUserResponse\"1\n" +
	"\x19ValidateAndGetUserRequest\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"/\n" +
	"\x13GetDanceByIDRequest\x12\x18\n" +
	"\aDanceId\x18\x01 \x01(\tR\aDanceId\"\x14\n" +
	"\x12GetMainPageRequest\"-\n" +
	"\tVideoItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\"T\n" +
	"\x13GetMainPageResponse\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\x12'\n" +
	"\x06Videos\x18\x02 \x03(\v2\x0f.auth.VideoItemR\x06Videos2\x97\a\n" +
	"\x04Auth\x127\n" +
	"\n" +
	"SignupUser\x12\x13.auth.SignupRequest\x1a\x12.auth.AuthResponse\"\x00\x127\n" +
	"\n" +
	"SignInUser\x12\x13.auth.SignInRequest\x1a\x12.auth.AuthResponse\"\x00\x12A\n" +
	"\n" +
	"LogOutUser\x12\x17.auth.LogOutUserRequest\x1a\x18.auth.LogOutUserResponse\"\x00\x125\n" +
	"\aGetUser\x12\x14.auth.GetUserRequest\x1a\x12.auth.UserResponse\"\x00\x12C\n" +
	"\x0eChangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\x12.auth.AuthResponse\"\x00\x12>\n" +
	"\tLoadDance\x12\x16.auth.LoadDanceRequest\x1a\x17.auth.LoadDanceResponse\"\x00\x12H\n" +
	"\x0eLoadDanceByURL\x12\x1b.auth.LoadDanceByURLRequest\x1a\x17.auth.LoadDanceResponse\"\x00\x12D\n" +
	"\fGetDanceByID\x12\x19.auth.GetDanceByIDRequest\x1a\x17.auth.LoadDanceResponse\"\x00\x12D\n" +
	"\vGetMainPage\x12\x18.auth.GetMainPageRequest\x1a\x19.auth.GetMainPageResponse\"\x00\x12K\n" +
	"\x12ValidateAndGetUser\x12\x1f.auth.ValidateAndGetUserRequest\x1a\x12.auth.UserResponse\"\x00\x12>\n" +
	"\tEnable2fa\x12\x16.auth.Enable2faRequest\x1a\x17.auth.Enable2faResponse\"\x00\x12A\n" +
	"\n" +
	"Disable2fa\x12\x17.auth.Disable2faRequest\x1a\x18.auth.Disable2faResponse\"\x00\x12;\n" +
	"\fSignUpUserVK\x12\x15.auth.SignupVKRequest\x1a\x12.auth.AuthResponse\"\x00\x12;\n" +
	"\fSignInUserVK\x12\x15.auth.SignupVKRequest\x1a\x12.auth.AuthResponse\"\x00B,Z*./internal/pkg/auth/delivery/grpc/gen/;genb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_auth_proto_goTypes = []any{
	(*SignupVKRequest)(nil),           // 0: auth.SignupVKRequest
	(*Enable2FaRequest)(nil),          // 1: auth.Enable2faRequest
	(*Enable2FaResponse)(nil),         // 2: auth.Enable2faResponse
	(*Disable2FaRequest)(nil),         // 3: auth.Disable2faRequest
	(*Disable2FaResponse)(nil),        // 4: auth.Disable2faResponse
	(*EmptyResponse)(nil),             // 5: auth.EmptyResponse
	(*UserResponse)(nil),              // 6: auth.UserResponse
	(*SignupRequest)(nil),             // 7: auth.SignupRequest
	(*SignInRequest)(nil),             // 8: auth.SignInRequest
	(*AuthResponse)(nil),              // 9: auth.AuthResponse
	(*GetUserRequest)(nil),            // 10: auth.GetUserRequest
	(*ChangePasswordRequest)(nil),     // 11: auth.ChangePasswordRequest
	(*LoadDanceRequest)(nil),          // 12: auth.LoadDanceRequest
	(*LoadDanceByURLRequest)(nil),     // 13: auth.LoadDanceByURLRequest
	(*LoadDanceResponse)(nil),         // 14: auth.LoadDanceResponse
	(*LogOutUserRequest)(nil),         // 15: auth.LogOutUserRequest
	(*LogOutUserResponse)(nil),        // 16: auth.LogOutUserResponse
	(*ValidateAndGetUserRequest)(nil), // 17: auth.ValidateAndGetUserRequest
	(*GetDanceByIDRequest)(nil),       // 18: auth.GetDanceByIDRequest
	(*GetMainPageRequest)(nil),        // 19: auth.GetMainPageRequest
	(*VideoItem)(nil),                 // 20: auth.VideoItem
	(*GetMainPageResponse)(nil),       // 21: auth.GetMainPageResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	6,  // 0: auth.AuthResponse.User:type_name -> auth.UserResponse
	20, // 1: auth.GetMainPageResponse.Videos:type_name -> auth.VideoItem
	7,  // 2: auth.Auth.SignupUser:input_type -> auth.SignupRequest
	8,  // 3: auth.Auth.SignInUser:input_type -> auth.SignInRequest
	15, // 4: auth.Auth.LogOutUser:input_type -> auth.LogOutUserRequest
	10, // 5: auth.Auth.GetUser:input_type -> auth.GetUserRequest
	11, // 6: auth.Auth.ChangePassword:input_type -> auth.ChangePasswordRequest
	12, // 7: auth.Auth.LoadDance:input_type -> auth.LoadDanceRequest
	13, // 8: auth.Auth.LoadDanceByURL:input_type -> auth.LoadDanceByURLRequest
	18, // 9: auth.Auth.GetDanceByID:input_type -> auth.GetDanceByIDRequest
	19, // 10: auth.Auth.GetMainPage:input_type -> auth.GetMainPageRequest
	17, // 11: auth.Auth.ValidateAndGetUser:input_type -> auth.ValidateAndGetUserRequest
	1,  // 12: auth.Auth.Enable2fa:input_type -> auth.Enable2faRequest
	3,  // 13: auth.Auth.Disable2fa:input_type -> auth.Disable2faRequest
	0,  // 14: auth.Auth.SignUpUserVK:input_type -> auth.SignupVKRequest
	0,  // 15: auth.Auth.SignInUserVK:input_type -> auth.SignupVKRequest
	9,  // 16: auth.Auth.SignupUser:output_type -> auth.AuthResponse
	9,  // 17: auth.Auth.SignInUser:output_type -> auth.AuthResponse
	16, // 18: auth.Auth.LogOutUser:output_type -> auth.LogOutUserResponse
	6,  // 19: auth.Auth.GetUser:output_type -> auth.UserResponse
	9,  // 20: auth.Auth.ChangePassword:output_type -> auth.AuthResponse
	14, // 21: auth.Auth.LoadDance:output_type -> auth.LoadDanceResponse
	14, // 22: auth.Auth.LoadDanceByURL:output_type -> auth.LoadDanceResponse
	14, // 23: auth.Auth.GetDanceByID:output_type -> auth.LoadDanceResponse
	21, // 24: auth.Auth.GetMainPage:output_type -> auth.GetMainPageResponse
	6,  // 25: auth.Auth.ValidateAndGetUser:output_type -> auth.UserResponse
	2,  // 26: auth.Auth.Enable2fa:output_type -> auth.Enable2faResponse
	4,  // 27: auth.Auth.Disable2fa:output_type -> auth.Disable2faResponse
	9,  // 28: auth.Auth.SignUpUserVK:output_type -> auth.AuthResponse
	9,  // 29: auth.Auth.SignInUserVK:output_type -> auth.AuthResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	file_proto_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_auth_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
