// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/check": {
            "get": {
                "description": "Verify if user is authenticated and return user data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check authentication status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clear authentication cookie and log out user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "description": "Authenticate user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignInInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Register a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/change/password": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет пароль, возвращает обновлённый JWT и CSRF-токен в куках и заголовке X-CSRF-Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Изменить пароль текущего пользователя",
                "parameters": [
                    {
                        "description": "Старый и новый пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChangePasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/dance/{dance_id}/segment/{segment_idx}": {
            "get": {
                "security": [
                    {
                        "OptionalAuth": []
                    }
                ],
                "description": "Возвращает описание для указанного сегмента танца",
                "tags": [
                    "dances"
                ],
                "summary": "Получить текстовое описание сегмента танца",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID танца",
                        "name": "dance_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Индекс сегмента (начиная с 0)",
                        "name": "segment_idx",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SegmentDescriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Танец или сегмент не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/dance/{id}": {
            "get": {
                "security": [
                    {
                        "OptionalAuth": []
                    }
                ],
                "description": "Возвращает метаданные обработанного танца",
                "tags": [
                    "dances"
                ],
                "summary": "Получить информацию о танце по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID танца",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoadDanceResponse"
                        }
                    },
                    "400": {
                        "description": "Не указан ID танца",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Танец не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список ранее загруженных или просмотренных танцев текущего пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "История поиска пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SearchHistoryItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/history/{history_id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Изменяет пользовательское название для указанной записи истории",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить название записи в истории",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID записи истории",
                        "name": "history_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новое название",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateHistoryNameInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Название успешно обновлено"
                    },
                    "400": {
                        "description": "Неверный ID записи или тело запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет запись истории по её ID, принадлежащую текущему пользователю",
                "tags": [
                    "users"
                ],
                "summary": "Удалить запись из истории поиска",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID записи истории",
                        "name": "history_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Запись успешно удалена"
                    },
                    "400": {
                        "description": "Неверный ID записи",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/load": {
            "post": {
                "security": [
                    {
                        "OptionalAuth": []
                    }
                ],
                "description": "Принимает видеофайл через multipart/form-data, конвертирует в H.264 и отправляет на анализ",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dances"
                ],
                "summary": "Загрузить видео танца и обработать его",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Видеофайл (до 60 МБ)",
                        "name": "dance",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoadDanceResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка чтения файла или неверный запрос",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "413": {
                        "description": "Файл слишком большой",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/loadByURL": {
            "post": {
                "security": [
                    {
                        "OptionalAuth": []
                    }
                ],
                "description": "Принимает JSON с URL, скачивает видео и обрабатывает его",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dances"
                ],
                "summary": "Загрузить танец по URL видео",
                "parameters": [
                    {
                        "description": "URL видео",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoadDanceByURLInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoadDanceResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или отсутствует URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Видео не найдено",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/main_page": {
            "get": {
                "security": [
                    {
                        "OptionalAuth": []
                    }
                ],
                "description": "Возвращает массив танцев (возможно, популярных или недавних)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dances"
                ],
                "summary": "Получить список танцев для главной страницы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MainPageResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает публичные данные пользователя (ID, версию, логин, аватар)",
                "tags": [
                    "users"
                ],
                "summary": "Получить информацию о пользователе по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Неверный формат ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ChangePasswordInput": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "models.LoadDanceByURLInput": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "models.LoadDanceResponse": {
            "type": "object",
            "required": [
                "dance_id",
                "duration_sec",
                "full_glb_key",
                "glb_keys",
                "num_frames",
                "num_segments",
                "num_segments_rendered",
                "segments_key",
                "video_path"
            ],
            "properties": {
                "dance_id": {
                    "type": "string"
                },
                "duration_sec": {
                    "type": "number"
                },
                "full_glb_key": {
                    "type": "string"
                },
                "glb_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "num_frames": {
                    "type": "integer"
                },
                "num_segments": {
                    "type": "integer"
                },
                "num_segments_rendered": {
                    "type": "integer"
                },
                "segments_key": {
                    "type": "string"
                },
                "video_path": {
                    "type": "string"
                }
            }
        },
        "models.MainPageResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VideoItem"
                    }
                }
            }
        },
        "models.SearchHistoryItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "dance_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.SegmentDescriptionResponse": {
            "type": "object",
            "properties": {
                "dance_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "segment_idx": {
                    "type": "integer"
                }
            }
        },
        "models.SignInInput": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_code": {
                    "type": "string"
                }
            }
        },
        "models.SignUpInput": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.UpdateHistoryNameInput": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "avatar",
                "has_2fa",
                "id",
                "is_foreign",
                "login",
                "version"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "has_2fa": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "is_foreign": {
                    "type": "boolean"
                },
                "login": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "models.VideoItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5458",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "DDDance API",
	Description:      "API для авторизации пользователей и получения разбора танца.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
